### PR TITLE
Parsing for shogi moves

### PR DESCRIPTION
**Pull request by birtles**

### CODE REVIEW

**Comment by SaltfishAmi** [comment]
I really did not expect this feature... and seriously I won't be able to provide a zh-hans translation for these terms. Not even got a clue about what do they mean.

**Comment by birtles** [comment]
> I really did not expect this feature... and seriously I won't be able to provide a zh-hans translation for these terms. Not even got a clue about what do they mean.

Yes, it was a suggestion from Twitter. I don't think many people will use it, to be honest. I have made the zh-hans localization just mirror the Japanese strings (which are probably not particuarly helpful!) and I think it's fine to leave it like that.

**Comment by nicolasmaia** [comment]
I noticed that the word ドキュメンテーション triggers shogi parsing. Is that intentional?

**Comment by birtles** [comment]
> I noticed that the word ドキュメンテーション triggers shogi parsing. Is that intentional?

Yes, that's a known bug (the previously reported case being ドクター). I mean, it's somewhat intentional, but I think we need to now show the shogi translation unless it's the longest match -- at least for the shogi shorthand.

**Pull request merged**
