### PR TITLE
chore: introduce tailwind setup for popup styles

### PR DESCRIPTION
**Pull request by birtles**
Still to do:
- [x] Convert remaining reference table styles (possibly try using [tailwindcss-container-queries](https://github.com/tailwindlabs/tailwindcss-container-queries) instead of media queries)
- [x] Try adding an option to the fixture decorator to toggle the base font size
- [x] Try adding an option to the fixture decorator to toggle the root font size
- [x] Try adding a [prefix](https://tailwindcss.com/docs/configuration#prefix) to the generated classes so that when we load `popup.css` and `options.css` in the same page they don't clash
- [x] See if we can get rid of the `!entry`-related classes added to the popup stylesheet

### CODE REVIEW

**Comment by birtles** [comment]
Needs testing but I think this is pretty close. I still need to convert a few more of the references tables styles before it's ready though.

It would be nice to add something to the popup fixture decorator that allows toggling the base font size so we can confirm that everything scales as expected (and maybe even something to change the root font size so we can verify we're not using `rem` units).

cc @StarScape

**Comment by birtles** [comment]
I hit an issue today where I discovered that in React Cosmos we are generating a CSS file that includes the styles from `popup.css` _and_ `options.css` and using that for every component. (What's more, because both `@import` `themes.css` it appears twice in the output.)

I dug into it a bit and it looks like it's a limitation of the way React Cosmos works where it imports all the fixtures into a single entrypoint such that all the styles they reference get combined.

I don't _think_ that's causing problems for us at the moment but it's not ideal so I posted a suggestion over on the React Cosmos project: https://github.com/react-cosmos/react-cosmos/discussions/1638

I tried to work around this by not referencing the styles at all from JS and just generating the CSS files separately and referencing them by name but React Cosmos' webpack plugin doesn't allow you to define extra entrypoints for generating the CSS files.

**Comment by birtles** [comment]
Needs testing on each of the different browsers but otherwise this PR should be about ready.

**Comment by birtles** [comment]
I've tested this on Firefox and Chrome and it seems fine. I need to get to the office to test Safari and Thunderbird but if anyone else wants to give it a try that would help.

**Comment by StarScape** [comment]
I’d be happy to test on Safari today @birtles.

**Comment by StarScape** [comment]
Tested on iOS Safari and everything looks A-okay.

**Comment by birtles** [comment]
> Tested on iOS Safari and everything looks A-okay.

Thanks @StarScape!

I just tested on Edge and it looks ok. I haven't tested on Thunderbird but I'll test that before releasing.

**Pull request merged**
