### PR TITLE
fix: prevent rendering of verb class tags on proverbs

### LINKED ISSUE #1469: Hide verb classes on proverbs
As reported by email,

> [It was recently decided](https://github.com/JMdictProject/JMdictIssues/issues/69) to include verb class tags on proverb entries to facilitate handling of inflected forms. You may want to hide these tags as they're not really intended for users (given that proverbs typically don't conjugate).

### PR DESCRIPTION
**Pull request by Enellis**
Fixes #1469.

### CODE REVIEW

**Comment by Enellis** [comment]
Is it good to be explicit here? We could also check whether the tag begins with a `v`.
According to the [docs](http://edrdg.org/jmdict/jmdict_dtd_h.html) the only conflicting one would be `vulg`.

**Comment by birtles** [comment]
> Is it good to be explicit here? We could also check whether the tag begins with a `v`. According to the [docs](http://edrdg.org/jmdict/jmdict_dtd_h.html) the only conflicting one would be `vulg`.

This looks great. Thank you!

I'd personally probably lean towards just checking whether the tag begins with a 'v' (and is not 'vulg') for simplicity's sake. We'll have a bug if a new tag that starts with 'v' is introduced _and_ applied to a proverb but that seems unlikely.

(Even when explicitly listing out the verb tags it's also not entirely impossible for future changes to introduce regressions since there may be new verb types added since some of the JMdict verb tags are a bit arbitrary).

That said I'm quite happy to accept this as-is. What do you think?

**Comment by birtles** [comment]
I'm going to go ahead and merge this as-is so that I can set up a release. (I can only create releases for Safari from a Mac, currently, and I won't be near a Mac until at least Tuesday. If I set up the release today then hopefully I can publish it in a day or two after I get confirmation that the fix for #1802 is ok.)

**Comment by Enellis** [comment]
Thanks for the feedback and merge!

Let's see how the verb class tags develop in the future. We can still revisit this approach at that time.

**Pull request merged**
